version: "3"
 
services:
  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/generatepdf
      - gems:/gems
 
 
volumes:
  gems:
